runtime: python37

service: backend

handlers:
- url: /.*
  script: auto

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'true'
  PROJECT_ID : 'fir-project-f8aa4'

entrypoint: gunicorn -b :$PORT main:app
  


