runtime: python27
api_version: 1
threadsafe: true
service: backend

handlers:
- url: /.*
  script: main.app

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'true'
  PROJECT_ID : 'fir-project-f8aa4'
  
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*$
- ^(.*/)?node_modules$
- ^venv$

